# Projeto FIAP Fase 4

## Get Database

In [68]:
import yfinance as yf
import numpy as np
import matplotlib.pyplot as plt
import datetime
import pandas as pd
import os
import sys

In [69]:
list_symbol = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META']

start_date = '2002-01-01'
end_date = '2026-04-20'

In [70]:
df = yf.download(list_symbol, start=start_date, end=end_date)

df_index_ajusted = df.stack(level=1).reset_index()

df_index_ajusted

[*********************100%***********************]  5 of 5 completed
/var/folders/h0/9cxt3flx6px_mz8j5myq3cjw0000gn/T/ipykernel_13700/296897865.py:3: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_index_ajusted = df.stack(level=1).reset_index()

Price,Date,Ticker,Close,High,Low,Open,Volume
0,2002-01-02,AAPL,0.349069,0.349069,0.328994,0.330342,529496800.0
1,2002-01-02,AMZN,0.548000,0.550000,0.524000,0.546500,130392000.0
2,2002-01-02,MSFT,20.429262,20.450593,19.963022,20.310417,48124000.0
3,2002-01-03,AAPL,0.353264,0.355811,0.341129,0.344574,612007200.0
4,2002-01-03,AMZN,0.595000,0.597000,0.552500,0.556500,217514000.0
...,...,...,...,...,...,...,...
27279,2026-04-17,AAPL,270.230011,272.299988,266.720001,266.959991,61436200.0
27280,2026-04-17,AMZN,250.559998,256.179993,250.110001,254.990005,52029300.0
27281,2026-04-17,GOOGL,341.679993,342.320007,336.239990,337.649994,25581900.0
27282,2026-04-17,META,688.549988,691.520020,675.130005,678.599976,16283500.0
27283,2026-04-17,MSFT,422.790009,431.579987,420.690002,424.820007,48568200.0

In [71]:
df_index_ajusted.describe()

Price,Date,Close,High,Low,Open,Volume
count,27284,27284.000000,27284.000000,27284.000000,27284.000000,2.728400e+04
mean,2015-01-25 19:11:11.866295296,90.344040,91.331769,89.298839,90.326663,1.425267e+08
min,2002-01-02 00:00:00,0.196558,0.197606,0.190565,0.194610,4.726100e+06
25%,2009-06-08 00:00:00,13.313077,13.476463,13.167226,13.328280,3.213912e+07
50%,2015-06-11 00:00:00,33.434975,33.779584,33.142955,33.426264,6.334415e+07
75%,2020-11-09 00:00:00,135.719006,137.238734,134.173932,135.721226,1.370256e+08
max,2026-04-17 00:00:00,788.148987,794.384398,778.990557,789.296390,3.372970e+09
std,NaN,122.617898,123.982809,121.197709,122.638057,2.316138e+08

In [72]:
df_index_ajusted.isna().sum()

Price
Date      0
Ticker    0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [73]:
df_index_ajusted.dtypes

Price
Date      datetime64[ns]
Ticker            object
Close            float64
High             float64
Low              float64
Open             float64
Volume           float64
dtype: object

In [74]:
import sqlite3

In [75]:
# ensure the database directory exists before connecting
db_dir = "./src/database"
os.makedirs(db_dir, exist_ok=True)

In [76]:
db_path = os.path.abspath(os.path.join(db_dir, "bronze.db"))

In [77]:
db_path

'/Users/viniciussouza/Codes/FIAP/FIAP_projeto_fase_4/src/notebooks/src/database/bronze.db'

In [78]:
conn = sqlite3.connect(db_path)
conn

In [79]:
df_index_ajusted.to_sql("stocks_raw", conn, if_exists="replace", index=False)

27284

In [80]:
conn.close()

In [81]:
conn = sqlite3.connect("./src/database/bronze.db")
teste = pd.read_sql("SELECT * FROM stocks_raw", conn)

In [82]:
teste

,Date,Ticker,Close,High,Low,Open,Volume
0,2002-01-02 00:00:00,AAPL,0.349069,0.349069,0.328994,0.330342,529496800.0
1,2002-01-02 00:00:00,AMZN,0.548000,0.550000,0.524000,0.546500,130392000.0
2,2002-01-02 00:00:00,MSFT,20.429262,20.450593,19.963022,20.310417,48124000.0
3,2002-01-03 00:00:00,AAPL,0.353264,0.355811,0.341129,0.344574,612007200.0
4,2002-01-03 00:00:00,AMZN,0.595000,0.597000,0.552500,0.556500,217514000.0
...,...,...,...,...,...,...,...
27279,2026-04-17 00:00:00,AAPL,270.230011,272.299988,266.720001,266.959991,61436200.0
27280,2026-04-17 00:00:00,AMZN,250.559998,256.179993,250.110001,254.990005,52029300.0
27281,2026-04-17 00:00:00,GOOGL,341.679993,342.320007,336.239990,337.649994,25581900.0
27282,2026-04-17 00:00:00,META,688.549988,691.520020,675.130005,678.599976,16283500.0
27283,2026-04-17 00:00:00,MSFT,422.790009,431.579987,420.690002,424.820007,48568200.0